apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://gitlab.cee.redhat.com/rhidp/rhdh/-/tree/{{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "7"
    pipelinesascode.tekton.dev/on-cel-expression: |
      (event == "push" || event == "pull_request") && 
      target_branch == "rhdh-{{VERSION_DOT}}-rhel-9" && 
      ( "distgit/containers/rhdh-hub/***".pathChanged() || ".tekton/rhdh-hub-{{VERSION_DASH}}.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rhdh-{{VERSION_DASH}}
    appstudio.openshift.io/component: rhdh-hub-{{VERSION_DASH}}
    pipelines.appstudio.openshift.io/type: build
  name: rhdh-hub-{{VERSION_DASH}}
  namespace: rhdh-tenant
spec:
  params:
    # Component identification
    - name: rhdh-version
      value: "{{VERSION_DASH}}"
    - name: component-type
      value: hub
    - name: DO_HELM
      value: "true"
    - name: IS_BUNDLE
      value: "false"
    - name: skip-checks
      value: "false"
    - name: hermetic
      value: "true"

    - name: build-source-image
      value: "true"
    - name: build-image-index
      value: "true"
    - name: build-args
      value: []
    - name: build-args-file
      value: ""
    # Common build parameters
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: source-branch
      value: '{{source_branch}}'
    - name: target_branch
      value: '{{target_branch}}'
    - name: event-type
      value: '{{event}}'
    - name: output-image
      value: quay.io/rhdh/rhdh-hub-rhel9:{{revision}}
    - name: image-expires-after
      value: ''
    - name: dockerfile
      value: Containerfile
    - name: path-context
      value: distgit/containers/rhdh-hub
    - name: prefetch-input
      value: '[{"type": "rpm", "path": "distgit/containers/rhdh-hub"},{"type": "yarn","path": "distgit/containers/rhdh-hub"},{"type": "yarn","path": "distgit/containers/rhdh-hub/dynamic-plugins"},{"type": "pip","path": "distgit/containers/rhdh-hub/python", "allow_binary": "false"}]'
  pipelineRef:
    name: build-pipeline-rhdh-hub
  taskRunSpecs:
    - pipelineTaskName: build-container-hub
      stepSpecs:
      - name: build
        computeResources:
          requests:
            cpu: '8'
            memory: 20Gi
          limits:
            cpu: '8'
            memory: 20Gi
    - pipelineTaskName: prefetch-dependencies-hub
      computeResources:
        requests:
          cpu: '8'
          memory: 12Gi
        limits:
          cpu: '8'
          memory: 12Gi
  taskRunTemplate:
    serviceAccountName: build-pipeline-rhdh-hub-{{VERSION_DASH}}
  timeouts:
    pipeline: 3h
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}

