# Copyright (c) 2023-2024 Red Hat, Inc.
# requires yarn npm prettifier husky
# requires python3-pip npm git jq rsync
# requires yq (python wrapper for jq)
# see also upstream_repos.yml

.shared_config:
  tags:
    # old docker and shared runners will expire at the end of March 2025
    # - docker
    # - shared
    # try using new runners - see https://issues.redhat.com/browse/RHIDP-5735
    - shared-podman
  # for RHDH 1.3 use builder-latest; for 1.4+ (Yarn 3) use yarn3-latest
  # image: quay.io/rhdh/gitlab-runner:builder-latest
  image: quay.io/rhdh/gitlab-runner:yarn3-latest
  allow_failure: false
  # see https://gitlab.cee.redhat.com/help/ci/runners/configure_runners.md#configure-runner-behavior-with-variables for what can be set here
  variables:
    # SECURE_FILES_DOWNLOAD_PATH: '.secure_files'
    GIT_DEPTH: "0"
    GIT_FETCH_EXTRA_FLAGS: --prune
  artifacts:
    expire_in: 8 hours

workflow:
  rules:
    # run if not a merge request or if scheduled
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' || $CI_PIPELINE_SOURCE == "schedule"
    # don't run on default branch rhdh-1-rhel-9, only on stable branches rhdh-1-yy-rhel-9 for now
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never

stages:
  - sync-midstream

include:
  - local: "/build/ci/sync-midstream.yml"
