# Copyright (c) 2023 Red Hat, Inc.
# requires yarn npm prettifier husky
# requires python3-pip npm git jq rsync
# requires yq (python wrapper for jq)
# see also upstream_repos.yml

.shared_config:
  tags:
    - docker
    - shared
  image: registry.redhat.io/ubi9
  allow_failure: false
  # see https://gitlab.cee.redhat.com/help/ci/runners/configure_runners.md#configure-runner-behavior-with-variables for what can be set here
  variables:
    # SECURE_FILES_DOWNLOAD_PATH: '.secure_files'
    GIT_DEPTH: "0"
    GIT_FETCH_EXTRA_FLAGS: --prune

workflow:
  rules:
    # run if not a merge request or scheduled
    - if: $CI_PIPELINE_SOURCE != 'merge_request_event' || $CI_PIPELINE_SOURCE == "schedule"
    # don't run on default branch rhdh-1-rhel-9, only on stable branches rhdh-1-yy-rhel-9 for now
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never

stages:
  - sync-midstream
  - sync-downstream
  - build-downstream
  - copy-to-quay
  - publish-helmchart
  - review-stages

include:
  - local: "/build/ci/sync-midstream-sync-downstream-build-downstream.yml"
  - local: "/build/ci/copy-to-quay.yml"
  - local: "/build/ci/publish-helmchart.yml"

review-stages:
  extends: .shared_config
  stage: review-stages
  script:
    - |
      dnf -y -q install git findutils
      cat outputs*/*
      set +e
      if [[ $(find . -name "outputs*") ]]; then
        NUM_SKIPS=$(cat outputs*/*.txt | grep " Nothing to" | wc -l)
        echo "[INFO] Total of $NUM_SKIPS stages were skipped."
        # if number of skipped stages > 0, fail this stage so it's clear this wasn't an actual respin
        set -e
        exit $NUM_SKIPS
      else
        echo "No artifacts from previous stages found!"
        set -e
        exit 13
      fi
