ARG PRISTINE_IMAGE
FROM $PRISTINE_IMAGE AS sealights

# hadolint ignore=DL3002
USER 0

ARG BSID AGENT_VERSION

ENV BSID=${BSID} AGENT_VERSION=${AGENT_VERSION} \
    SEALIGHTS_TOKEN_FILE=/opt/app-root/src/sl-token NODE_DEBUG=sl FRONTEND_BUILD_DIR=dist SL_FRONTEND_BUILD_DIR=sl_dist

RUN npm install -g slnodejs@${AGENT_VERSION}

USER root
RUN --mount=type=secret,id=sealights-credentials/token cp /run/secrets/sealights-credentials/token $SEALIGHTS_TOKEN_FILE
RUN chmod +r ${SEALIGHTS_TOKEN_FILE}
USER 1001

RUN slnodejs scan --tokenfile $SEALIGHTS_TOKEN_FILE --buildsessionid $BSID --scm none --instrumentForBrowsers \
    --projectroot "$CONTAINER_SOURCE" --excludedpaths webpack --workspacepath "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" \
    --outputpath "$CONTAINER_SOURCE/packages/app/${SL_FRONTEND_BUILD_DIR}" --uniqueModuleId frontend

RUN slnodejs scan --tokenfile $SEALIGHTS_TOKEN_FILE --buildsessionid $BSID --scm none \
    --projectroot "$CONTAINER_SOURCE" --workspacepath "$CONTAINER_SOURCE/packages/backend" --uniqueModuleId backend

RUN slnodejs buildend --buildsessionid $BSID --tokenfile $SEALIGHTS_TOKEN_FILE --ok

RUN rm -rf "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" && \
    mv "$CONTAINER_SOURCE/packages/app/${SL_FRONTEND_BUILD_DIR}" "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}"

ENTRYPOINT ["/bin/sh", "-c", "slnodejs run --buildsessionid ${BSID} --workspacepath . --useinitialcolor true --tokenfile ${SEALIGHTS_TOKEN_FILE} -- --require ./instrumentation.js packages/backend --config app-config.yaml --config app-config.example.yaml --config app-config.example.production.yaml"]
