ARG PRISTINE_IMAGE
FROM $PRISTINE_IMAGE AS sealights

ARG BSID AGENT_VERSION

ENV SL_buildSessionId=${BSID} AGENT_VERSION=${AGENT_VERSION} \
    SL_tokenFile=/opt/app-root/src/sltoken.txt NODE_DEBUG=sl FRONTEND_BUILD_DIR=dist SL_FRONTEND_BUILD_DIR=sl_dist

RUN npm install -g slnodejs@${AGENT_VERSION} && npm cache clean --force

USER root
RUN --mount=type=secret,id=sealights-credentials/token cp /run/secrets/sealights-credentials/token $SL_tokenFile
RUN chmod +r ${SL_tokenFile}
RUN chown 1001 ${SL_tokenFile}
USER 1001

# Update source map relative paths to absolute paths before scanning (plugins only).
RUN cd $CONTAINER_SOURCE && \
    for map_file in $(find plugins -path "*/dist/*.map" -type f); do \
        if grep -q '"sources"' "$map_file"; then \
            plugin_base=${map_file%/dist/*}; \
            sed -i -E "s|\"(\\.\\.?/)+([^\"]*)\"|\"$CONTAINER_SOURCE/$plugin_base/\\2\"|g" "$map_file"; \
        fi; \
    done

# Declare the plugin list as an ENV variable
ENV PLUGIN_LIST="dynamic-plugins-info-backend licensed-users-info-backend scalprum-backend dynamic-plugins-info"

# Define common scan parameters
ENV SL_SCAN_BASE="slnodejs scan --tokenfile $SL_tokenFile --buildsessionid $SL_buildSessionId --excludedpaths webpack --scm none --projectroot $CONTAINER_SOURCE"

# Scan modules with browser instrumentation (frontend and app-next)
RUN $SL_SCAN_BASE --workspacepath "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" --uniqueModuleId frontend
RUN $SL_SCAN_BASE --workspacepath "$CONTAINER_SOURCE/packages/app-next/dist" --uniqueModuleId app-next

# Scan backend module
RUN $SL_SCAN_BASE --workspacepath "$CONTAINER_SOURCE/packages/backend" --uniqueModuleId backend

# Scan plugins using array iteration
RUN for plugin in $PLUGIN_LIST; do \
        $SL_SCAN_BASE --workspacepath "$CONTAINER_SOURCE/plugins/$plugin/dist" --uniqueModuleId $plugin; \
    done

RUN slnodejs buildend --buildsessionid $SL_buildSessionId --tokenfile $SL_tokenFile --ok

# Define common instrument parameters
ENV SL_INSTRUMENT_BASE="slnodejs instrument --tokenfile $SL_tokenFile --buildsessionid $SL_buildSessionId --projectroot $CONTAINER_SOURCE"

# Instrument frontend
RUN $SL_INSTRUMENT_BASE \
    --workspacepath "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" \
    --outputpath "$CONTAINER_SOURCE/packages/app/${SL_FRONTEND_BUILD_DIR}" && \
    rm -rf "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" && \
    mv "$CONTAINER_SOURCE/packages/app/${SL_FRONTEND_BUILD_DIR}" "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}"

# Instrument app-next
RUN $SL_INSTRUMENT_BASE \
    --workspacepath "$CONTAINER_SOURCE/packages/app-next/dist" \
    --outputpath "$CONTAINER_SOURCE/packages/app-next/sl_dist" && \
    rm -rf "$CONTAINER_SOURCE/packages/app-next/dist" && \
    mv "$CONTAINER_SOURCE/packages/app-next/sl_dist" "$CONTAINER_SOURCE/packages/app-next/dist"


RUN echo ${SL_buildSessionId} > buildSessionId

ENV NODE_OPTIONS="${NODE_OPTIONS} --require /opt/app-root/src/.npm-global/lib/node_modules/slnodejs/lib/preload.js" \
    SL_workspacepath="." \
    SL_useinitialcolor="true" \
    SL_buildSessionIdFile="/opt/app-root/src/buildSessionId" \
    SL_disableCoverageSummaryLogs="true" \
    NODE_DEBUG=""

# append Brew metadata here
ENV SUMMARY="Red Hat Developer Hub container" \
    DESCRIPTION="Red Hat Developer Hub container" \
    RHDH_VERSION="1.8.0" \
    BACKSTAGE_VERSION="1.42.5" \
    UPSTREAM_REPO="https://github.com/redhat-developer/rhdh/tree/main @ 2624e76e" \
    MIDSTREAM_REPO="https://gitlab.cee.redhat.com/rhidp/rhdh/-/commits/rhdh-1-rhel-9" \
    PRODNAME="rhdh" \
    COMPNAME="hub"

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$DESCRIPTION" \
      io.openshift.tags="$PRODNAME,$COMPNAME" \
      com.redhat.component="$PRODNAME-$COMPNAME-container" \
      name="$PRODNAME/$PRODNAME-$COMPNAME-rhel9" \
      version="1.8" \
      release="120" \
      license="ASLv2" \
      maintainer="RHDH Team <rhdh-bot@redhat.com>" \
      vendor="Red Hat, Inc." \
      io.openshift.expose-services="" \
      usage="" \
      konflux.additional-tags="next, 1.8, 1.8-120" \
      distribution-scope="public" \
      url="https://red.ht/rhdh"
