ARG PRISTINE_IMAGE
FROM $PRISTINE_IMAGE AS sealights

ARG BSID AGENT_VERSION

ENV SL_buildSessionId=${BSID} AGENT_VERSION=${AGENT_VERSION} \
    SL_tokenFile=/opt/app-root/src/sltoken.txt NODE_DEBUG=sl FRONTEND_BUILD_DIR=dist SL_FRONTEND_BUILD_DIR=sl_dist

RUN npm install -g slnodejs@${AGENT_VERSION}

USER root
RUN --mount=type=secret,id=sealights-credentials/token cp /run/secrets/sealights-credentials/token $SL_tokenFile
RUN chmod +r ${SL_tokenFile}
RUN chown 1001 ${SL_tokenFile}
USER 1001

RUN slnodejs scan --tokenfile $SL_tokenFile --buildsessionid $SL_buildSessionId --scm none --instrumentForBrowsers \
    --projectroot "$CONTAINER_SOURCE" --excludedpaths webpack --workspacepath "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" \
    --outputpath "$CONTAINER_SOURCE/packages/app/${SL_FRONTEND_BUILD_DIR}" --uniqueModuleId frontend

RUN slnodejs scan --tokenfile $SL_tokenFile --buildsessionid $SL_buildSessionId --scm none \
    --projectroot "$CONTAINER_SOURCE" --workspacepath "$CONTAINER_SOURCE/packages/backend" --uniqueModuleId backend

RUN slnodejs buildend --buildsessionid $SL_buildSessionId --tokenfile $SL_tokenFile --ok

RUN rm -rf "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}" && \
    mv "$CONTAINER_SOURCE/packages/app/${SL_FRONTEND_BUILD_DIR}" "$CONTAINER_SOURCE/packages/app/${FRONTEND_BUILD_DIR}"

RUN echo ${SL_buildSessionId} > buildSessionId

ENV NODE_OPTIONS="${NODE_OPTIONS} --require /opt/app-root/src/.npm-global/lib/node_modules/slnodejs/lib/preload.js" \
    SL_workspacepath="." \
    SL_useinitialcolor="true" \
    SL_buildSessionIdFile="/opt/app-root/src/buildSessionId" \
    SL_disableCoverageSummaryLogs="true" \
    NODE_DEBUG=""

# append Brew metadata here
ENV SUMMARY="Red Hat Developer Hub container" \
    DESCRIPTION="Red Hat Developer Hub container" \
    UPSTREAM_REPO="https://github.com/redhat-developer/rhdh/tree/main @ 4c3b18ff" \
    MIDSTREAM_REPO="https://gitlab.cee.redhat.com/rhidp/rhdh/-/commits/rhdh-1-rhel-9" \
    PRODNAME="rhdh" \
    COMPNAME="hub"

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$DESCRIPTION" \
      io.openshift.tags="$PRODNAME,$COMPNAME" \
      com.redhat.component="$PRODNAME-$COMPNAME-container" \
      name="$PRODNAME/$PRODNAME-$COMPNAME-rhel9" \
      version="1.7" \
      release="114" \
      license="ASLv2" \
      maintainer="RHDH Team <rhdh-bot@redhat.com>" \
      vendor="Red Hat, Inc." \
      io.openshift.expose-services="" \
      usage="" \
      konflux.additional-tags="next, 1.7, 1.7-114" \
      distribution-scope="public" \
      url="https://red.ht/rhdh"
