#
#
# Copyright Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:161a4e29ea482bab6048c2b36031b4f302ae81e4ff18b83e61785f40dc576f5d AS rag-assets-downloader

ARG RAG_ASSETS_URL="https://github.com/redhat-ai-dev/rhdh-rag-content/releases/download/rag-assets-rhdh-1.9-lls-0.5.0/rag-assets-rhdh-1.9-lls-0.5.0.tar.gz"

USER 0
WORKDIR /tmp/rag-assets

RUN microdnf install -y tar gzip && microdnf clean all
RUN test -n "${RAG_ASSETS_URL}" && \
    curl -fsSL "${RAG_ASSETS_URL}" -o rag-assets.tar.gz && \
    mkdir -p extracted && \
    tar --no-same-owner --no-same-permissions -C extracted -xzf rag-assets.tar.gz && \
    test -d extracted/vector_db/rhdh_product_docs && \
    test -d extracted/embeddings_model

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7@sha256:161a4e29ea482bab6048c2b36031b4f302ae81e4ff18b83e61785f40dc576f5d

COPY --from=rag-assets-downloader /tmp/rag-assets/extracted/vector_db/rhdh_product_docs /rag/vector_db/rhdh_product_docs
COPY --from=rag-assets-downloader /tmp/rag-assets/extracted/embeddings_model /rag/embeddings_model

USER 65532:65532

ENV SUMMARY="Red Hat Developer Hub RAG content" \
DESCRIPTION="Red Hat Developer Hub RAG content" \
RHDH_VERSION="1.10.0" \
BACKSTAGE_VERSION="1.49.4" \
UPSTREAM_REPO="https://github.com/redhat-ai-dev/rhdh-rag-content/tree/main @ c2866262" \
MIDSTREAM_REPO="https://gitlab.cee.redhat.com/rhidp/rhdh/-/commits/rhdh-1-rhel-9" \
PRODNAME="rhdh" \
COMPNAME="rag-content"

LABEL summary="$SUMMARY" \
    description="$DESCRIPTION" \
    io.k8s.description="$DESCRIPTION" \
    io.k8s.display-name="$DESCRIPTION" \
    io.openshift.tags="$PRODNAME,$COMPNAME" \
    com.redhat.component="$PRODNAME-$COMPNAME-container" \
    name="$PRODNAME/$PRODNAME-rhel9-$COMPNAME" \
    version="1.10" \
    release="1" \
    license="ASLv2" \
    maintainer="RHDH Team <rhdh-bot@redhat.com>" \
    vendor="Red Hat, Inc." \
    io.openshift.expose-services="" \
    usage="" \
    konflux.additional-tags="next, 1.10, 1.10-1" \
    distribution-scope="public" \
    url="https://red.ht/rhdh" \
    cpe="cpe:/a:redhat:rhdh:1.10::el9"
