apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: fbc-fips-check-idms
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/rhdh
    source: registry.redhat.io/rhdh
  - mirrors:
    - quay.io/rhdh
    source: registry.stage.redhat.io/rhdh
  mirrorSourcePolicy: AllowContactingSource
