# THIS IS USED BY Konflux builds >= 1.4

# RHIDP-4220 - make Konflux preflight and EC checks happy - need some layer with RPMs even if not doing any pre-processing work
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as builder-runner
USER 1001

FROM scratch

# Copy files to locations specified by labels.
COPY manifests /manifests/
COPY metadata /metadata/

# RHIDP-4220 - make Konflux preflight and EC checks happy - [check-container] Create a directory named /licenses and include all relevant licensing
COPY licenses /licenses/

# append Brew metadata here
ENV SUMMARY="Red Hat Developer Hub operator bundle" \
    DESCRIPTION="Red Hat Developer Hub operator bundle" \
    RHDH_VERSION="1.8.0" \
    BACKSTAGE_VERSION="1.42.5" \
    UPSTREAM_REPO="https://github.com/redhat-developer/rhdh-operator/tree/main @ 516d216a" \
    MIDSTREAM_REPO="https://gitlab.cee.redhat.com/rhidp/rhdh/-/commits/rhdh-1-rhel-9" \
    PRODNAME="rhdh" \
    COMPNAME="operator-bundle"

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1 \
      operators.operatorframework.io.bundle.manifests.v1=manifests/ \
      operators.operatorframework.io.bundle.metadata.v1=metadata/ \
      operators.operatorframework.io.bundle.package.v1=rhdh \
      operators.operatorframework.io.bundle.channels.v1=fast,fast-1.8 \
      operators.operatorframework.io.bundle.channel.default.v1=fast \
      com.redhat.delivery.operator.bundle="true" \
      com.redhat.openshift.versions="v4.12" \
      com.redhat.delivery.backport=false \
      summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$DESCRIPTION" \
      io.openshift.tags="$PRODNAME,$COMPNAME" \
      com.redhat.component="$PRODNAME-$COMPNAME-container" \
      name="$PRODNAME/$PRODNAME-$COMPNAME" \
      version="1.8" \
      vendor="Red Hat, Inc." \
      release="90" \
      license="ASLv2" \
      maintainer="RHDH Team <rhdh-bot@redhat.com>" \
      io.openshift.expose-services="" \
      usage="" \
      konflux.additional-tags="next, 1.8, 1.8-90" \
      distribution-scope="public" \
      url="https://red.ht/rhdh"
