# THIS IS USED BY Konflux builds >= 1.4
# RHIDP-4220 - make Konflux preflight and EC checks happy - need some layer with RPMs even if not doing any pre-processing work
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as builder-runner

RUN microdnf install -y skopeo python3.11 python3.11-pip npm git jq rsync findutils && \
alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
alternatives --install /usr/bin/pip pip /usr/bin/pip3.11 1 && \
pip install --upgrade pip && pip install yq

# Use a new stage to enable caching of the package installations for local development
FROM builder-runner as builder

COPY /build /sync /midstream/build
COPY /sync /midstream/sync
COPY /upstream_repos.yml /midstream/
COPY distgit/containers/rhdh-operator-bundle /midstream/distgit/containers/rhdh-operator-bundle

WORKDIR /midstream/

RUN git init; bash -x ./build/ci/update-bundle.sh --container-nudge

FROM scratch

# RHIDP-4220 - make Konflux preflight and EC checks happy - [check-container] Create a directory named /licenses and include all relevant licensing
COPY --from=builder /midstream/distgit/containers/rhdh-operator-bundle/manifests /manifests/
COPY --from=builder /midstream/distgit/containers/rhdh-operator-bundle/metadata /metadata/
COPY --from=builder /midstream/distgit/containers/rhdh-operator-bundle/licenses /licenses/

# append Brew metadata here
ENV SUMMARY="Red Hat Developer Hub operator bundle" \
    DESCRIPTION="Red Hat Developer Hub operator bundle" \
    UPSTREAM_REPO="https://github.com/redhat-developer/rhdh-operator/tree/main @ 7cd7a4c2" \
    MIDSTREAM_REPO="https://gitlab.cee.redhat.com/rhidp/rhdh/-/commits/rhdh-1-rhel-9" \
    PRODNAME="rhdh" \
    COMPNAME="operator-bundle"

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1 \
      operators.operatorframework.io.bundle.manifests.v1=manifests/ \
      operators.operatorframework.io.bundle.metadata.v1=metadata/ \
      operators.operatorframework.io.bundle.package.v1=rhdh \
      operators.operatorframework.io.bundle.channels.v1=fast,fast-1.5 \
      operators.operatorframework.io.bundle.channel.default.v1=fast \
      com.redhat.delivery.operator.bundle="true" \
      com.redhat.openshift.versions="v4.12" \
      com.redhat.delivery.backport=false \
      summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$DESCRIPTION" \
      io.openshift.tags="$PRODNAME,$COMPNAME" \
      com.redhat.component="$PRODNAME-$COMPNAME-container" \
      name="$PRODNAME/$PRODNAME-$COMPNAME" \
      version="1.5" \
      vendor="Red Hat, Inc." \
      release="88" \
      license="ASLv2" \
      maintainer="RHDH Team <rhdh-bot@redhat.com>" \
      io.openshift.expose-services="" \
      usage="" \
      konflux.additional-tags="next, 1.5, 1.5-88" \
      distribution-scope="public" \
      url="https://red.ht/rhdh"
