# Release Guide for RHDH Plugins and Catalog Index

[IMPORTANT]
====
DRAFT DOC IN PROGRESS

This process is still evolving and subject to change. Once we have a stable process for building plugins and the catalog index, onboarding + building the plugins will need to happen BEFORE the operator bundle build.
====

See https://issues.redhat.com/browse/RHIDP-7097

### Create branches

This will create branches and do the initial onboarding of a prod sec version for RHDH, plus pyxis and k-r-d stuff for RHDH.

For the Plugin Catalog, see subsequent steps below.

```
./build/scripts/tagRelease.sh
```

#### Purge Konflux-generated MRs and branches

Once the k-r-d MR is merged, Konflux may generate new pipelines in the `1.y` branch, which should be ignored and closed.

Purge branches with:

```
for branch in $(git branch -a | grep remotes/origin/konflux- | sed -r -e "s|remotes/origin/||"); do git push origin :$branch; done
```

Then close the MRs in batches: 

https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/merge_requests/?sort=updated_desc&state=opened&author_username=project_112031_bot_7effa89ba961de1dc1ce4830a29db90e&first_page_size=20

The above steps may no longer be necessary. See https://issues.redhat.com/browse/RHIDP-9369 which hopefully prevents creation of unnecessary MRs. 

### Plugin Catalog - rhdh-1-rhel-9 branch:

Check out the new rhdh-1-rhel-9 branch, then:

1. Remove plugin_builds/ content + regenerate; review changes and merge manually, or re-run without the --nopush flag to push directly
```
./build/ci/sync-midstream.sh --force -b rhdh-1-rhel-9 --nopush
```

2. Onboad new plugins to Konflux (if any); update 1.next pipelines
+ 
For each of the scripts run, review changes and merge manually, or re-run without the --nopush flag to generate MRs
+
```
export QUAY_TOKEN=...

./build/scripts/generatePyxisConfigForPlugins.sh -v 1.9.0 --clean --nopush
./build/scripts/generateKonfluxReleaseDataForPlugins.sh -v 1.next --clean --nopush

# wait up to 15 mins for new components to appear on the cluster (?)

cd .tekton; ./generatePipelineRunsForPlugins.sh -v 1.next --clean --nopush 
		<< not working, pagerduty-bsp and backend missing
```

### Plugin Catalog - rhdh-1.y-rhel-9 branch:

Check out the new rhdh-1.y-rhel-9 branch, then:

1. Remove plugin_builds/ content + regenerate; review changes and merge manually, or re-run without the --nopush flag to push directly
```
VERSION=1.8
./build/ci/sync-midstream.sh --force -b rhdh-1.y-rhel-9 --nopush
```

2. Onboad new 1.y plugin to Konflux; remove 1.next pipelines from the 1.y branch
+ 
For each of the scripts run, review changes and merge manually, or re-run without the --nopush flag to generate MRs
```
rm -fr .tekton/*-1-push*

export QUAY_TOKEN=...

./build/scripts/generatePyxisConfigForPlugins.sh -v 1.8.0 --clean --nopush
./build/scripts/generateKonfluxReleaseDataForPlugins.sh -v 1.8.0 --clean --nopush

# wait up to 15 mins for new components to appear on the cluster (?)

cd .tekton; ./generatePipelineRunsForPlugins.sh -v 1.8.0 --clean --nopush 
		<< not working, pagerduty-bsp and backend missing?
```
