# Release Guide for RHDH Plugins and Catalog Index

[IMPORTANT]
====
DRAFT DOC IN PROGRESS

This process is still evolving and subject to change. Once we have a stable process for building plugins and the catalog index, onboarding + building the plugins will need to happen BEFORE the operator bundle build.
====

See https://issues.redhat.com/browse/RHIDP-7097

## Build orchestration

Plugins respins will be triggered in Konflux if a change is synced from the https://github.com/redhat-developer/rhdh-plugin-export-overlays/ repo into the https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/ repo.

In that case, if the commit updates one of the workspaces/* folders listed in the `on-cel-expression` in the pipelineRuns defined in the link:https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/tree/rhdh-1-rhel-9/.tekton[rhdh-plugin-catalog/.tekton] folder, that build will fire.

If no change has happened in the overlays repo or the workspaces/ folders but you need to respin, you can still trigger a respin manually. 

This is accomplished by committing a change to the pipelineRun yaml file, which will trigger Konflux to re-run it. There are two ways to do this efficiently, when many plugins need to be rebuilt.

### Respin 1 or more specific plugin pipelineRuns

To respin a single plugin pipelineRun, or a set of pipelineRuns matching a regular expression, use link:https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/blob/rhdh-1-rhel-9/.tekton/generatePipelineRunsForPlugins.sh[.tekton/generatePipelineRunsForPlugins.sh] with the `--trigger` flag.

You can either specify a `--regex` like `quay` to match all the quay plugins, scaffoldersm etc.

Or use the `--path` flag to point to a single workspace plugin folder, like link:https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/tree/rhdh-1-rhel-9/workspaces/quay/plugins/quay-actions[quay/plugins/quay-actions]

### Check status of plugins, and respin several plugins pipelineRuns

To check Quay for tags matching the expected values in the link:https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/tree/rhdh-1-rhel-9/plugin_builds[plugin_builds] folder, you can use the link:https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/blob/rhdh-1-rhel-9/build/scripts/checkPluginsExist.sh[checkPluginsExist.sh] script.

The script will generate a list of quay images and expected tags, plus report on missing plugins (either the quay repo is missing, or the repo exists but the tag is missing).

Optionally, you can use this script to also trigger respins using link:https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/blob/rhdh-1-rhel-9/.tekton/generatePipelineRunsForPlugins.sh[.tekton/generatePipelineRunsForPlugins.sh]

 with one of the --trigger flags:
* respin only missing plugins (or missing tags): `--trigger-missing`
* respin existing plugins: `--trigger-existing`
* respin all plugins: `--trigger-all`


## RC Day

### Create branches

This will create branches and do the initial onboarding of a prod sec version for RHDH, plus pyxis and k-r-d stuff for RHDH.

For the Plugin Catalog, see subsequent steps below.

```
./build/scripts/tagRelease.sh
```

#### Purge Konflux-generated MRs and branches

Once the k-r-d MR is merged, Konflux may generate new pipelines in the `1.y` branch, which should be ignored and closed.

Purge branches with:

```
for branch in $(git branch -a | grep remotes/origin/konflux- | sed -r -e "s|remotes/origin/||"); do git push origin :$branch; done
```

Then close the MRs in batches: 

https://gitlab.cee.redhat.com/rhidp/rhdh-plugin-catalog/-/merge_requests/?sort=updated_desc&state=opened&author_username=project_112031_bot_7effa89ba961de1dc1ce4830a29db90e&first_page_size=20

The above steps may no longer be necessary. See https://issues.redhat.com/browse/RHIDP-9369 which hopefully prevents creation of unnecessary MRs. 

### Plugin Catalog - rhdh-1-rhel-9 branch:

Check out the new rhdh-1-rhel-9 branch, then:

1. Remove plugin_builds/ content + regenerate; review changes and merge manually, or re-run without the --nopush flag to push directly
```
./build/ci/sync-midstream.sh --force -b rhdh-1-rhel-9 --nopush
```
+
2. Onboad new plugins to Konflux (if any); update 1.next pipelines
+ 
For each of the scripts run, review changes and merge manually, or re-run without the --nopush flag to generate MRs
+
```
export QUAY_TOKEN=...

./build/scripts/generatePyxisConfigForPlugins.sh -v 1.9.0 --clean --nopush
./build/scripts/generateKonfluxReleaseDataForPlugins.sh -v 1.next --clean --nopush

# wait up to 15 mins for new components to appear on the cluster (?)

cd .tekton; ./generatePipelineRunsForPlugins.sh -v 1.next --clean --nopush 
		<< not working, pagerduty-bsp and backend missing
```

### Plugin Catalog - rhdh-1.y-rhel-9 branch:

Check out the new rhdh-1.y-rhel-9 branch, then:

1. Remove plugin_builds/ content + regenerate; review changes and merge manually, or re-run without the --nopush flag to push directly
```
VERSION=1.8
./build/ci/sync-midstream.sh --force -b rhdh-1.y-rhel-9 --nopush
```
+
2. Onboad new 1.y plugin to Konflux; remove 1.next pipelines from the 1.y branch
+ 
For each of the scripts run, review changes and merge manually, or re-run without the --nopush flag to generate MRs
```
rm -fr .tekton/*-1-push*

export QUAY_TOKEN=...

./build/scripts/generatePyxisConfigForPlugins.sh -v 1.8.0 --clean --nopush
./build/scripts/generateKonfluxReleaseDataForPlugins.sh -v 1.8.0 --clean --nopush

# wait up to 15 mins for new components to appear on the cluster (?)

cd .tekton; ./generatePipelineRunsForPlugins.sh -v 1.8.0 --clean --nopush 
		<< not working, pagerduty-bsp and backend missing?
```
